#!/usr/bin/env python3
# Generated by meson-jll v0.0.3
"""Strips every file Meson just installed into libdir, using whichever
strip tool Meson found. See the meson-jll comment that generated this
file for why this exists.

Usage: strip_libs.py <strip-tool> <libdir-relative-path>
"""
import os
import subprocess
import sys


def main():
    strip_tool, libdir = sys.argv[1:3]

    # MESON_INSTALL_DESTDIR_PREFIX is only known once `meson install`
    # actually runs (it can be overridden with --destdir or --prefix at
    # install time), so the libdir this script strips is resolved here,
    # never baked into the command Meson was configured with.
    destdir_prefix = os.environ["MESON_INSTALL_DESTDIR_PREFIX"]
    target_dir = os.path.join(destdir_prefix, libdir)
    if not os.path.isdir(target_dir):
        return

    for name in os.listdir(target_dir):
        path = os.path.join(target_dir, name)
        if os.path.isfile(path):
            # check=False: a stray non-object file left in libdir should
            # not fail the whole install, only skip stripping.
            subprocess.run([strip_tool, "--strip-all", path], check=False)


if __name__ == "__main__":
    main()
