#!/usr/bin/env python3
# Generated by meson-jll v0.0.3
"""Strips one file with the given strip tool, falling back to a plain copy
if the strip tool fails on it. See the meson-jll comment that generated
this file for why this exists.

Usage: strip_or_copy.py <strip-tool> <input-path> <output-path>
"""
import shutil
import subprocess
import sys


def main():
    strip_tool, input_path, output_path = sys.argv[1:4]
    result = subprocess.run(
        [strip_tool, "--strip-all", "-o", output_path, input_path]
    )
    if result.returncode != 0:
        shutil.copyfile(input_path, output_path)


if __name__ == "__main__":
    main()
